# ====================================================
# =                      SCALARS                     =
# ====================================================
scalar Time
scalar BigDecimal
scalar UUID

# ====================================================
# =                      TYPES                       =
# ====================================================

# ====================================================
# =                      INPUTS                      =
# ====================================================

input PageInput {
    page: Int! = 0
    size: Int! = 20
    sort: [SortInput!] = [{field: "id", direction: ASC}]
}

input SortInput {
    field: String!
    direction: SortDirection! = ASC
}

# ====================================================
# =                      ENUMS                       =
# ====================================================

enum SortDirection {
    ASC
    DESC
}