# ====================================================
# =                      TYPES                       =
# ====================================================
"Линзы"
type Lens implements ProductInterface {
    "Идентификатор пар линз"
    id: String!

    "Категория товара"
    category: ProductType!

    "Дата создания линз"
    createdAt: Time!

    "Автор добавления линз"
    createdBy: Int!

    "Название линз"
    name: String!

    "Описание линз"
    description: String

    "Цвет линз"
    color: String!

    "Бренд линз"
    brand: String!

    "Актуальная цена линз"
    actualPrice: BigDecimal!

    "Минимальная оптическая сила"
    minOpticalPower: BigDecimal!

    "Минимальная оптическая сила"
    maxOpticalPower: BigDecimal!

    "Шаг оптической силы"
    opticalPowerStep: BigDecimal!

    "Имеются нулевки?"
    hasZeroOpticalPower: Boolean!

    "Диаметр линз"
    diameter: BigDecimal!

    "Радиус кривизны линз"
    curvatureRadius: BigDecimal!

    "Доступное количество пар линз"
    quantity: Int!

    "Количество продаж"
    salesQuantity: Int!

    "Доступны линзы?"
    isAvailable: Boolean!

    "Удалена линза?"
    isDeleted: Boolean!
}

# ====================================================
# =                      INPUTS                      =
# ====================================================
input LensSearchInput {
    "Цвет линз"
    color: [String!]

    "Оптическая сила"
    opticalPower: BigDecimal

    "Имеются нулевки?"
    hasZeroOpticalPower: Boolean

    "Бренд линз"
    brand: [String]!

    "Диаметр линз"
    diameter: BigDecimal

    "Радиус кривизны линз"
    curvatureRadius: BigDecimal

    "Линза удалена?"
    isDeleted: Boolean

    "Доступна линза?"
    isAvailable: Boolean
}