package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/dkhvan-dev/product-service/internal/factory"
	"github.com/dkhvan-dev/product-service/internal/products"
	"github.com/dkhvan-dev/product-service/src/graph/model"
	"github.com/dkhvan-dev/product-service/src/utils"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, pageable model.PageInput, types []model.ProductType, search *model.ProductSearchInput) (*model.ProductPage, error) {
	utils.SetDefaults(&pageable)
	var response []model.ProductUnion
	for _, t := range types {
		store, err := factory.ProductStoreFactory.Get(t.String())
		if err != nil {
			return nil, err
		}

		result, err := store.(products.ProductService).FindAll(pageable, utils.SelectedFields(ctx), search)
		if err != nil {
			return nil, err
		}

		response = append(response, result.Content...)
	}

	return &model.ProductPage{Content: response, TotalElements: len(response)}, nil
}

// ProductBestSellers is the resolver for the productBestSellers field.
func (r *queryResolver) ProductBestSellers(ctx context.Context) ([]*model.ProductBestSeller, error) {
	productStore := products.ProductStore{}
	result, err := productStore.BestSellers(factory.ProductStoreFactory.BestSellersMap)
	if err != nil {
		return nil, err
	}

	if len(result) > 6 {
		return result[:6], nil
	}

	return result, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
