package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"github.com/dkhvan-dev/product-service/internal/factory"
	"github.com/dkhvan-dev/product-service/src/utils"

	"github.com/dkhvan-dev/product-service/src/graph/model"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, pageable model.PageInput, productType model.ProductType) (*model.ProductPage, error) {
	utils.SetDefaults(&pageable)
	store, err := factory.ProductStoreFactory.Get(productType.String())
	if err != nil {
		return nil, err
	}

	result, err := store.FindAll(pageable, utils.SelectedFields(ctx))
	if err != nil {
		return nil, err
	}

	return result, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
