// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type ProductInterface interface {
	IsProductInterface()
	// Идентификатор
	GetID() int
	// Дата создания товара
	GetCreatedAt() time.Time
	// Автор добавления товара
	GetCreatedBy() int
	// Название товара
	GetName() string
	// Описание товара
	GetDescription() *string
}

// Линзы
type Lens struct {
	// Идентификатор пар линз
	ID int `json:"id"`
	// Дата создания линз
	CreatedAt time.Time `json:"createdAt"`
	// Автор добавления линз
	CreatedBy int `json:"createdBy"`
	// Название линз
	Name string `json:"name"`
	// Описание линз
	Description *string `json:"description,omitempty"`
	// Модель линз
	Model *LensModel `json:"model"`
	// Бренд линз
	Brand string `json:"brand"`
	// Актуальная цена линз
	ActualPrice *LensPriceHistory `json:"actualPrice"`
	// Цвет линз
	Color string `json:"color"`
	// Оптическая сила линз
	OpticalPower float64 `json:"opticalPower"`
	// Диаметр линз
	Diameter float64 `json:"diameter"`
	// Радиус кривизны линз
	CurvatureRadius float64 `json:"curvatureRadius"`
	// Доступны линзы?
	IsAvailable bool `json:"isAvailable"`
	// Доступное количество пар линз
	Quantity int `json:"quantity"`
}

func (Lens) IsProductInterface() {}

// Идентификатор
func (this Lens) GetID() int { return this.ID }

// Дата создания товара
func (this Lens) GetCreatedAt() time.Time { return this.CreatedAt }

// Автор добавления товара
func (this Lens) GetCreatedBy() int { return this.CreatedBy }

// Название товара
func (this Lens) GetName() string { return this.Name }

// Описание товара
func (this Lens) GetDescription() *string { return this.Description }

// Модель линз
type LensModel struct {
	// Идентификатор модели линз
	ID int `json:"id"`
	// Дата добавления модели линз
	CreatedAt time.Time `json:"createdAt"`
	// Автор добавления модели линз
	CreatedBy int `json:"createdBy"`
	// Название модели линз
	Name string `json:"name"`
	// Доступна модель линз?
	IsAvailable bool `json:"isAvailable"`
}

// История цен линз
type LensPriceHistory struct {
	// Идентификатор цены линз
	ID int `json:"id"`
	// Дата создания цены линз
	CreatedAt time.Time `json:"createdAt"`
	// Цена
	Price float64 `json:"price"`
}

type PageInput struct {
	Page int          `json:"page"`
	Size int          `json:"size"`
	Sort []*SortInput `json:"sort,omitempty"`
}

type ProductPage struct {
	Content       []ProductInterface `json:"content"`
	TotalElements int                `json:"totalElements"`
}

type Query struct {
}

type SortInput struct {
	Field     string        `json:"field"`
	Direction SortDirection `json:"direction"`
}

type ProductType string

const (
	// Линзы
	ProductTypeLenses ProductType = "LENSES"
)

var AllProductType = []ProductType{
	ProductTypeLenses,
}

func (e ProductType) IsValid() bool {
	switch e {
	case ProductTypeLenses:
		return true
	}
	return false
}

func (e ProductType) String() string {
	return string(e)
}

func (e *ProductType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductType", str)
	}
	return nil
}

func (e ProductType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
